### ISSUE TITLE
Useless scroll bars surrounding java code

### ISSUE THREAD

**Issue by squilter** [3drobotics/sphinx_3dr_theme#9]
See [here](http://android.dronekit.io/first_app.html) for an example.  This doesn't seem to happen to `.. codeblock:: xml` but it does happen to `.. codeblock:: java`

![capture](https://cloud.githubusercontent.com/assets/2956460/7522259/02a7b26a-f4c2-11e4-9a1f-947e0c15c126.JPG)

**Comment by mrpollo** [comment]
@hamishwillee can you please confirm and debug?

**Comment by hamishwillee** [comment]
@mrpollo, @squilter  Sure. I'll look into it today.

**Comment by hamishwillee** [comment]
Yes, its a bug. Fixed by pull request #10. You will need to push that live (and to PIP).

**Comment by squilter** [comment]
I am still seeing this issue [here](http://android.dronekit.io/first_app.html)

**Comment by hamishwillee** [comment]
@kaitlynhova @mrpollo This is valid so reopening. Assigning to Kaitlyn as I can't properly debug until I can rebuild the environment.

**Comment by kaitlynhova** [comment]
@hamishwillee  where are you seeing the java code scroll bars? I can't find any on the Android docs

**Comment by squilter** [comment]
I see it under the heading "Connecting to 3DR Services" on this page: http://android.dronekit.io/first_app.html

**Comment by kaitlynhova** [comment]
ah, gotcha! I made a PR for Ramon to merge and push to production for ya: 

https://github.com/3drobotics/sphinx_3dr_theme/pull/37

**Comment by hamishwillee** [comment]
Thanks @kaitlynhova !
